import { defineSlotRecipe } from '@pandacss/dev'

export const angleSlider = defineSlotRecipe({
	className: 'angleSlider',
	slots: ['control', 'thumb', 'marker'],
	base: {
		control: {
			'--size': '240px',
			'--thumb-size': '80px',
			'--thumb-indicator-size': 'min(var(--thumb-size), calc(var(--size) / 2))',
			pos: 'relative',
			display: 'flex',
			bg: 'whitesmoke',
			alignItems: 'center',
			justifyContent: 'center',
			userSelect: 'none',
			w: 'var(--size)',
			h: 'var(--size)',
			rounded: 'full',
		},
		thumb: {
			pos: 'absolute',
			top: 0,
			right: 0,
			left: 'calc(50% - 2px)',
			bottom: 0,
			w: '4px',
			h: 'full',
			pointerEvents: 'none',
			outline: 'none',
			_before: {
				content: '""',
				pos: 'absolute',
				top: 0,
				right: 0,
				w: '4px',
				h: 'var(--thumb-indicator-size)',
				bg: 'gray.900',
			},
		},
		marker: {
			pos: 'absolute',
			top: 0,
			bottom: 0,
			left: 'calc(50% - 1px)',
			w: '2px',
			_before: {
				content: '""',
				pos: 'absolute',
				top: 'calc(var(--thumb-size) / 3)',
				left: '.5px',
				w: '1px',
				h: 'calc(var(--thumb-size) / 1.5)',
				transform: 'translate(-50%, -50%)',
				bg: 'gray.500',
			},
		},
	},
})
