import { defineSlotRecipe } from '@pandacss/dev'

export const carousel = defineSlotRecipe({
	className: 'carousel',
	slots: [
		'root',
		'item',
		'prevTrigger',
		'nextTrigger',
		'indicatorGroup',
		'indicator',
	],
	base: {
		root: { pos: 'relative' },
		prevTrigger: {
			pos: 'absolute',
			top: '50%',
			transform: 'translateY(-50%)',
			left: 0,
			zIndex: 1,
			bg: 'white',
			p: 2,
			cursor: 'pointer',
			_disabled: {
				opacity: 0.5,
				cursor: 'default',
				pointerEvents: 'none',
			},
		},
		nextTrigger: {
			pos: 'absolute',
			top: '50%',
			transform: 'translateY(-50%)',
			right: 0,
			zIndex: 1,
			bg: 'white',
			p: 2,
			cursor: 'pointer',
			_disabled: {
				opacity: 0.5,
				cursor: 'default',
				pointerEvents: 'none',
			},
		},
		indicatorGroup: {
			bg: 'white',
			borderWidth: 1,
			borderColor: 'white',
			py: 1.5,
			px: 2,
			display: 'flex',
			alignItems: 'center',
			gap: 1.5,
			pos: 'absolute',
			left: '50%',
			bottom: 4,
			transform: 'translateX(-50%)',
		},
		indicator: {
			w: 3,
			h: 3,
			rounded: 'full',
			cursor: 'pointer',
			bg: 'gray.600',
			'&[data-current]': {
				bg: 'green.600',
			},
		},
	},
})
